### ISSUE TITLE
Failed to register Collector of type ClassLoadingExports: The Collector exposes the same name multiple times: jvm_classes_loaded

### ISSUE THREAD

**Issue by JJena** [johrstrom/jmeter-prometheus-plugin#124]
I have a custom built jar that I need to use for my Jmeter java requests. However I can't add prometheus listener (v0.60) to it because of below error. PS: If I remove my custom jar then I don 't see the issue. Also I haven't used the listener inside the custom jar.

`2023-05-18 09:15:29,464 ERROR o.a.j.s.c.TestElementConverter: TestElement not instantiable: class com.github.johrstrom.listener.PrometheusListener
java.lang.reflect.InvocationTargetException: null
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.apache.jmeter.save.converters.TestElementConverter.unmarshal(TestElementConverter.java:102) ~[ApacheJMeter_core-5.5.jar:5.5]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readBareItem(AbstractCollectionConverter.java:132) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:66) ~[ApacheJMeter_core-5.5.jar:5.5]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readBareItem(AbstractCollectionConverter.java:132) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:66) ~[ApacheJMeter_core-5.5.jar:5.5]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.converters.collections.AbstractCollectionConverter.readBareItem(AbstractCollectionConverter.java:132) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.jmeter.save.converters.HashTreeConverter.unmarshal(HashTreeConverter.java:66) ~[ApacheJMeter_core-5.5.jar:5.5]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.jmeter.save.ScriptWrapperConverter.unmarshal(ScriptWrapperConverter.java:93) ~[ApacheJMeter_core-5.5.jar:5.5]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convert(TreeUnmarshaller.java:74) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.core.AbstractReferenceUnmarshaller.convert(AbstractReferenceUnmarshaller.java:72) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:68) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.convertAnother(TreeUnmarshaller.java:52) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.core.TreeUnmarshaller.start(TreeUnmarshaller.java:136) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.unmarshal(AbstractTreeMarshallingStrategy.java:32) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1421) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.XStream.unmarshal(XStream.java:1399) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.thoughtworks.xstream.XStream.fromXML(XStream.java:1284) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.apache.jmeter.save.SaveService.readTree(SaveService.java:446) ~[ApacheJMeter_core-5.5.jar:5.5]
	at org.apache.jmeter.save.SaveService.loadTree(SaveService.java:429) ~[ApacheJMeter_core-5.5.jar:5.5]
	at org.apache.jmeter.gui.action.Load.loadProjectFile(Load.java:129) ~[ApacheJMeter_core-5.5.jar:5.5]
	at org.apache.jmeter.gui.action.Load.loadProjectFile(Load.java:101) ~[ApacheJMeter_core-5.5.jar:5.5]
	at org.apache.jmeter.gui.action.LoadRecentProject.doActionAfterCheck(LoadRecentProject.java:71) ~[ApacheJMeter_core-5.5.jar:5.5]
	at org.apache.jmeter.gui.action.AbstractActionWithNoRunningTest.doAction(AbstractActionWithNoRunningTest.java:44) ~[ApacheJMeter_core-5.5.jar:5.5]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core-5.5.jar:5.5]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core-5.5.jar:5.5]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
Caused by: java.lang.IllegalArgumentException: Failed to register Collector of type ClassLoadingExports: The Collector exposes the same name multiple times: jvm_classes_loaded
	at io.prometheus.client.CollectorRegistry.assertNoDuplicateNames(CollectorRegistry.java:71) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at io.prometheus.client.CollectorRegistry.register(CollectorRegistry.java:51) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at io.prometheus.client.Collector.register(Collector.java:308) ~[LoadTest-1.0.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at com.github.johrstrom.collector.JMeterCollectorRegistry.initDefaultExports(JMeterCollectorRegistry.java:52) ~[jmeter-prometheus-plugin-0.6.0.jar:?]
	at com.github.johrstrom.collector.JMeterCollectorRegistry.<init>(JMeterCollectorRegistry.java:40) ~[jmeter-prometheus-plugin-0.6.0.jar:?]
	at com.github.johrstrom.collector.JMeterCollectorRegistry.getInstance(JMeterCollectorRegistry.java:33) ~[jmeter-prometheus-plugin-0.6.0.jar:?]
	at com.github.johrstrom.collector.CollectorElement.<init>(CollectorElement.java:19) ~[jmeter-prometheus-plugin-0.6.0.jar:?]
	at com.github.johrstrom.listener.PrometheusListener.<init>(PrometheusListener.java:49) ~[jmeter-prometheus-plugin-0.6.0.jar:?]
	... 58 more
2023-05-18 09:15:29,792 WARN o.a.j.g.a.Load: Unexpected error. java.lang.NullPointerException
java.lang.NullPointerException: null
	at org.apache.jmeter.gui.GuiPackage.getGui(GuiPackage.java:224) ~[ApacheJMeter_core-5.5.jar:5.5]
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addComponent(JMeterTreeModel.java:160) ~[ApacheJMeter_core-5.5.jar:5.5]
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addSubTree(JMeterTreeModel.java:131) ~[ApacheJMeter_core-5.5.jar:5.5]
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addSubTree(JMeterTreeModel.java:131) ~[ApacheJMeter_core-5.5.jar:5.5]
	at org.apache.jmeter.gui.tree.JMeterTreeModel.addSubTree(JMeterTreeModel.java:123) ~[ApacheJMeter_core-5.5.jar:5.5]
	at org.apache.jmeter.gui.GuiPackage.addSubTree(GuiPackage.java:554) ~[ApacheJMeter_core-5.5.jar:5.5]
	at org.apache.jmeter.gui.action.Load.insertLoadedTree(Load.java:199) ~[ApacheJMeter_core-5.5.jar:5.5]
	at org.apache.jmeter.gui.action.Load.loadProjectFile(Load.java:130) ~[ApacheJMeter_core-5.5.jar:5.5]
	at org.apache.jmeter.gui.action.Load.loadProjectFile(Load.java:101) ~[ApacheJMeter_core-5.5.jar:5.5]
	at org.apache.jmeter.gui.action.LoadRecentProject.doActionAfterCheck(LoadRecentProject.java:71) ~[ApacheJMeter_core-5.5.jar:5.5]
	at org.apache.jmeter.gui.action.AbstractActionWithNoRunningTest.doAction(AbstractActionWithNoRunningTest.java:44) ~[ApacheJMeter_core-5.5.jar:5.5]
	at org.apache.jmeter.gui.action.ActionRouter.performAction(ActionRouter.java:87) ~[ApacheJMeter_core-5.5.jar:5.5]
	at org.apache.jmeter.gui.action.ActionRouter.lambda$actionPerformed$0(ActionRouter.java:69) ~[ApacheJMeter_core-5.5.jar:5.5]
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313) [?:?]
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:721) [?:?]
	at java.awt.EventQueue$4.run(EventQueue.java:715) [?:?]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:?]
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85) [?:?]
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:740) [?:?]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) [?:?]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) [?:?]
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) [?:?]
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:90) [?:?]
2023-05-18 09:15:29,793 ERROR o.a.j.u.JMeterUtils: Unexpected error - see log for details
`

**Comment by JJena** [comment]
After carefully looking at the dependency tree of my custom jar, I realized it was using prometheus simpleclient which had the same classes as this jmeter plugin. After excluding that dependency, it worked fine.
